/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SobreFranciscoRouteImport } from './routes/sobre-francisco'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as PoliticaCookiesRouteImport } from './routes/politica-cookies'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConsultoriaIaRouteImport } from './routes/consultoria-ia'
import { Route as CoachingTerapiaRouteImport } from './routes/coaching-terapia'
import { Route as CapacitacionCorporativaRouteImport } from './routes/capacitacion-corporativa'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreFranciscoRoute = SobreFranciscoRouteImport.update({
  id: '/sobre-francisco',
  path: '/sobre-francisco',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaCookiesRoute = PoliticaCookiesRouteImport.update({
  id: '/politica-cookies',
  path: '/politica-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaIaRoute = ConsultoriaIaRouteImport.update({
  id: '/consultoria-ia',
  path: '/consultoria-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingTerapiaRoute = CoachingTerapiaRouteImport.update({
  id: '/coaching-terapia',
  path: '/coaching-terapia',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacionCorporativaRoute = CapacitacionCorporativaRouteImport.update({
  id: '/capacitacion-corporativa',
  path: '/capacitacion-corporativa',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/capacitacion-corporativa': typeof CapacitacionCorporativaRoute
  '/coaching-terapia': typeof CoachingTerapiaRoute
  '/consultoria-ia': typeof ConsultoriaIaRoute
  '/contacto': typeof ContactoRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/sobre-francisco': typeof SobreFranciscoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/insights/': typeof InsightsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/capacitacion-corporativa': typeof CapacitacionCorporativaRoute
  '/coaching-terapia': typeof CoachingTerapiaRoute
  '/consultoria-ia': typeof ConsultoriaIaRoute
  '/contacto': typeof ContactoRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/sobre-francisco': typeof SobreFranciscoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/insights': typeof InsightsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/capacitacion-corporativa': typeof CapacitacionCorporativaRoute
  '/coaching-terapia': typeof CoachingTerapiaRoute
  '/consultoria-ia': typeof ConsultoriaIaRoute
  '/contacto': typeof ContactoRoute
  '/politica-cookies': typeof PoliticaCookiesRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/sobre-francisco': typeof SobreFranciscoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/chat': typeof ApiChatRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/insights/': typeof InsightsIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/capacitacion-corporativa'
    | '/coaching-terapia'
    | '/consultoria-ia'
    | '/contacto'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/sobre-francisco'
    | '/unsubscribe'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/insights/$slug'
    | '/sitemap/xml'
    | '/insights/'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/capacitacion-corporativa'
    | '/coaching-terapia'
    | '/consultoria-ia'
    | '/contacto'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/sobre-francisco'
    | '/unsubscribe'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/insights/$slug'
    | '/sitemap/xml'
    | '/insights'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/capacitacion-corporativa'
    | '/coaching-terapia'
    | '/consultoria-ia'
    | '/contacto'
    | '/politica-cookies'
    | '/politica-privacidad'
    | '/sobre-francisco'
    | '/unsubscribe'
    | '/api/chat'
    | '/email/unsubscribe'
    | '/insights/$slug'
    | '/sitemap/xml'
    | '/insights/'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CapacitacionCorporativaRoute: typeof CapacitacionCorporativaRoute
  CoachingTerapiaRoute: typeof CoachingTerapiaRoute
  ConsultoriaIaRoute: typeof ConsultoriaIaRoute
  ContactoRoute: typeof ContactoRoute
  PoliticaCookiesRoute: typeof PoliticaCookiesRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  SobreFranciscoRoute: typeof SobreFranciscoRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiChatRoute: typeof ApiChatRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-francisco': {
      id: '/sobre-francisco'
      path: '/sobre-francisco'
      fullPath: '/sobre-francisco'
      preLoaderRoute: typeof SobreFranciscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-cookies': {
      id: '/politica-cookies'
      path: '/politica-cookies'
      fullPath: '/politica-cookies'
      preLoaderRoute: typeof PoliticaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria-ia': {
      id: '/consultoria-ia'
      path: '/consultoria-ia'
      fullPath: '/consultoria-ia'
      preLoaderRoute: typeof ConsultoriaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching-terapia': {
      id: '/coaching-terapia'
      path: '/coaching-terapia'
      fullPath: '/coaching-terapia'
      preLoaderRoute: typeof CoachingTerapiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacion-corporativa': {
      id: '/capacitacion-corporativa'
      path: '/capacitacion-corporativa'
      fullPath: '/capacitacion-corporativa'
      preLoaderRoute: typeof CapacitacionCorporativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CapacitacionCorporativaRoute: CapacitacionCorporativaRoute,
  CoachingTerapiaRoute: CoachingTerapiaRoute,
  ConsultoriaIaRoute: ConsultoriaIaRoute,
  ContactoRoute: ContactoRoute,
  PoliticaCookiesRoute: PoliticaCookiesRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  SobreFranciscoRoute: SobreFranciscoRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiChatRoute: ApiChatRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
